import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  Linking,
  Platform,
  Alert,
  ScrollView,
  Modal,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { router } from "expo-router";
import Colors from "@/constants/colors";
import { FadeInView } from "@/components/FadeInView";
import { useAuth } from "@/contexts/AuthContext";

const APP_VERSION = "1.0.0";

const TERMS_SECTIONS = [
  {
    title: "Terms of Service — Verified GPS Camera",
    body: "Effective Date: February 27, 2026\n\nBy using the Verified GPS Camera app, you agree to the following terms. This App is operated by Aman Gupta (Admin).",
  },
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using the App, you agree to be bound by these Terms. If you do not agree, do not use the App.",
  },
  {
    title: "2. User Accounts & Tiers",
    body: "Guest Mode: Limited to 20 total photo uploads.\n\nStandard/Pro Tiers: Subject to daily and monthly upload limits as enforced by our backend.\n\nAccount Actions: The Admin reserves the right to upgrade, downgrade, or suspend any user account at any time via the Admin Panel.",
  },
  {
    title: "3. Usage & Security",
    body: "Anti-Hack Policy: The App uses internal security measures to verify photo authenticity. Any attempt to bypass GPS verification, upload unauthorized files, or spoof coordinates will result in an immediate permanent ban.\n\nUnauthorized Access: Users are prohibited from attempting to access the API or database directly.",
  },
  {
    title: "4. Data & Photos",
    body: "Ownership: You retain rights to your photos, but by uploading, you grant the App the right to process and store them for your use.\n\nAuto-Delete Policy: To maintain server performance, the App implements a nightly cleanup at 2:00 AM. Uploads exceeding the configured retention period (3, 6, or 12 months) will be permanently deleted.\n\nGPS Accuracy: While we provide real-time GPS overlays, the Admin is not responsible for any location deviations caused by hardware limitations or environmental factors.",
  },
  {
    title: "5. Disclaimer of Liability",
    body: "The App is provided \"as is\".\n\nThe Admin is not liable for any loss of data (photos), hardware damage, or legal issues arising from the use of geo-tagged photos generated by the App.",
  },
  {
    title: "6. Intellectual Property",
    body: "All branding, including the \"Verified GPS Camera\" name, logo, and unique serial number generation logic, is the property of Aman Gupta.",
  },
  {
    title: "7. Changes to Terms",
    body: "The Admin may update these terms at any time. Continued use of the App after changes constitutes acceptance of the new terms.",
  },
];

const PRIVACY_SECTIONS = [
  {
    title: "Privacy Policy — Verified GPS Camera",
    body: "Last Updated: February 27, 2026\n\nAt Verified GPS Camera, operated by Aman Gupta, we prioritize user privacy and data transparency. This policy explains our data practices for the Verified GPS Camera application.",
  },
  {
    title: "1. Information We Collect",
    body: "Location Data: We access real-time GPS coordinates (Latitude, Longitude) only when the camera is active to overlay verification data onto your photos.\n\nCamera Access: Required to capture photos within the App.",
  },
  {
    title: "2. Data Access & Storage",
    body: "No Access to Local Storage: We do not have access to your device's private gallery or any photos stored locally in the App's internal directory.\n\nUploaded Images Only: Our servers and the Admin can only access, process, and store images that you explicitly choose to upload via the Upload action.\n\nPrivate Offline Files: Any photo that remains in the Files tab without being uploaded is strictly private to your device and is never transmitted to our backend.",
  },
  {
    title: "3. Identity & Account Data",
    body: "We collect your email or phone number via Google Sign-In or OTP to manage your account tier and enforce upload limits (Guest, Standard, or Pro).",
  },
  {
    title: "4. Data Retention (Nightly Cleanup)",
    body: "Auto-Delete: To maintain server integrity, a nightly cleanup occurs at 2:00 AM. Uploaded photos are permanently deleted based on the set retention period (3, 6, or 12 months).\n\nSync Status: Uploaded photos show a green cloud badge; local-only photos show a grey cloud, indicating they are not on our servers.",
  },
  {
    title: "5. Security & Anti-Hack",
    body: "We use UUID generation and verification checks to ensure only authentic photos are processed. Unauthorized or spoofed files are blocked during the upload attempt.",
  },
  {
    title: "6. Contact & Support",
    body: "For data deletion requests or privacy concerns, contact:\n\nAman Gupta\nEmail: owsmboy7383@gmail.com",
  },
];

function SettingsRow({
  icon,
  label,
  value,
  onPress,
  destructive,
}: {
  icon: keyof typeof Ionicons.glyphMap;
  label: string;
  value?: string;
  onPress?: () => void;
  destructive?: boolean;
}) {
  return (
    <Pressable
      style={styles.row}
      onPress={onPress}
      disabled={!onPress}
      android_ripple={onPress ? { color: destructive ? Colors.light.rippleError : Colors.light.rippleNeutral } : undefined}
    >
      <View style={[styles.rowIcon, destructive && styles.rowIconDestructive]}>
        <Ionicons name={icon} size={18} color={destructive ? "#FF453A" : Colors.light.primary} />
      </View>
      <Text style={[styles.rowLabel, destructive && styles.rowLabelDestructive]}>{label}</Text>
      <View style={styles.rowRight}>
        {value ? <Text style={styles.rowValue}>{value}</Text> : null}
        {onPress ? (
          <Ionicons name="chevron-forward" size={16} color={Colors.light.textTertiary} />
        ) : null}
      </View>
    </Pressable>
  );
}

function SectionHeader({ title }: { title: string }) {
  return <Text style={styles.sectionHeader}>{title}</Text>;
}

export default function SettingsTab() {
  const insets = useSafeAreaInsets();
  const bottomInset = Platform.OS === "web" ? 34 : insets.bottom;
  const { isLoggedIn, user } = useAuth();
  const [showTerms, setShowTerms] = useState(false);
  const [showPrivacy, setShowPrivacy] = useState(false);

  const openUrl = async (url: string, label: string) => {
    const supported = await Linking.canOpenURL(url);
    if (supported) {
      await Linking.openURL(url);
    } else {
      Alert.alert("Cannot Open", `Could not open ${label}. URL: ${url}`);
    }
  };

  const handleAccountPress = () => {
    Alert.alert("Pro Account", "Unlimited uploads enabled.", [{ text: "OK" }]);
  };

  return (
    <FadeInView style={styles.container}>
      <ScrollView
        contentContainerStyle={[styles.content, { paddingBottom: bottomInset + 24 }]}
        showsVerticalScrollIndicator={false}
      >
        {/* Account */}
        <SectionHeader title="Account" />
        <View style={styles.card}>
          <Pressable
            style={styles.row}
            onPress={handleAccountPress}
            android_ripple={{ color: Colors.light.rippleNeutral }}
          >
            <View style={[styles.rowIcon, isLoggedIn && styles.rowIconAccount]}>
              {isLoggedIn ? (
                <Text style={styles.avatarText}>
                  {user?.phone ? user.phone.replace(/\D/g, "").slice(-1) : "U"}
                </Text>
              ) : (
                <Ionicons name="person-outline" size={18} color={Colors.light.primary} />
              )}
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.rowLabel}>
                {isLoggedIn ? (user?.phone ?? "Signed In") : "Sign In / Register"}
              </Text>
              {isLoggedIn && (
                <Text style={styles.rowSub}>
                  {user?.tier === "pro" ? "Pro" : "Standard"} · Tap to sign out
                </Text>
              )}
            </View>
            <Ionicons name="chevron-forward" size={16} color={Colors.light.textTertiary} />
          </Pressable>
        </View>

        {/* Data */}
        <SectionHeader title="Data" />
        <View style={styles.card}>
          <SettingsRow
            icon="trash-outline"
            label="Recycle Bin"
            onPress={() => router.push("/trash")}
          />
        </View>

        {/* App Info */}
        <SectionHeader title="About" />
        <View style={styles.card}>
          <SettingsRow icon="camera" label="App Name" value="Verified GPS Camera" />
          <View style={styles.divider} />
          <SettingsRow icon="code-slash-outline" label="Version" value={APP_VERSION} />
        </View>

        {/* Legal */}
        <SectionHeader title="Legal" />
        <View style={styles.card}>
          <SettingsRow
            icon="shield-checkmark-outline"
            label="Privacy Policy"
            onPress={() => setShowPrivacy(true)}
          />
          <View style={styles.divider} />
          <SettingsRow
            icon="document-text-outline"
            label="Terms of Service"
            onPress={() => setShowTerms(true)}
          />
        </View>

        {/* Support */}
        <SectionHeader title="Support" />
        <View style={styles.card}>
          <SettingsRow
            icon="mail-outline"
            label="Contact Support"
            onPress={() => openUrl("mailto:support@gpscamera.app", "email")}
          />
        </View>
      </ScrollView>

      {/* Terms of Service Modal */}
      <Modal visible={showTerms} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setShowTerms(false)}>
        <View style={[styles.termsContainer, { paddingTop: Platform.OS === "web" ? 67 : insets.top }]}>
          <View style={styles.termsHeader}>
            <Text style={styles.termsHeaderTitle}>Terms of Service</Text>
            <Pressable style={styles.termsCloseBtn} onPress={() => setShowTerms(false)} android_ripple={{ color: Colors.light.rippleNeutral, borderless: true }}>
              <Ionicons name="close" size={22} color={Colors.light.onSurface} />
            </Pressable>
          </View>
          <ScrollView contentContainerStyle={[styles.termsScroll, { paddingBottom: Platform.OS === "web" ? 34 : insets.bottom + 24 }]} showsVerticalScrollIndicator={false}>
            {TERMS_SECTIONS.map((section, i) => (
              <View key={i} style={styles.termsSection}>
                <Text style={[styles.termsSectionTitle, i === 0 && styles.termsSectionTitleMain]}>{section.title}</Text>
                <Text style={styles.termsSectionBody}>{section.body}</Text>
              </View>
            ))}
          </ScrollView>
        </View>
      </Modal>

      {/* Privacy Policy Modal */}
      <Modal visible={showPrivacy} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setShowPrivacy(false)}>
        <View style={[styles.termsContainer, { paddingTop: Platform.OS === "web" ? 67 : insets.top }]}>
          <View style={styles.termsHeader}>
            <Text style={styles.termsHeaderTitle}>Privacy Policy</Text>
            <Pressable style={styles.termsCloseBtn} onPress={() => setShowPrivacy(false)} android_ripple={{ color: Colors.light.rippleNeutral, borderless: true }}>
              <Ionicons name="close" size={22} color={Colors.light.onSurface} />
            </Pressable>
          </View>
          <ScrollView contentContainerStyle={[styles.termsScroll, { paddingBottom: Platform.OS === "web" ? 34 : insets.bottom + 24 }]} showsVerticalScrollIndicator={false}>
            {PRIVACY_SECTIONS.map((section, i) => (
              <View key={i} style={styles.termsSection}>
                <Text style={[styles.termsSectionTitle, i === 0 && styles.termsSectionTitleMain]}>{section.title}</Text>
                <Text style={styles.termsSectionBody}>{section.body}</Text>
              </View>
            ))}
          </ScrollView>
        </View>
      </Modal>
    </FadeInView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  sectionHeader: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: Colors.light.textSecondary,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginTop: 20,
    marginBottom: 6,
    marginLeft: 4,
  },
  card: {
    backgroundColor: Colors.light.cardBackground,
    borderRadius: 16,
    overflow: "hidden",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  rowIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.light.primaryContainer,
    justifyContent: "center",
    alignItems: "center",
  },
  rowIconDestructive: {
    backgroundColor: "rgba(255,69,58,0.12)",
  },
  rowLabel: {
    flex: 1,
    fontSize: 15,
    fontFamily: "Inter_500Medium",
    color: Colors.light.onSurface,
  },
  rowLabelDestructive: {
    color: "#FF453A",
  },
  rowIconAccount: {
    backgroundColor: Colors.light.primary,
  },
  avatarText: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: "#fff",
  },
  rowSub: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: Colors.light.textSecondary,
    marginTop: 1,
  },
  rowRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  rowValue: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: Colors.light.textSecondary,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Colors.light.outline,
    marginLeft: 60,
  },
  termsContainer: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  termsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.light.outline,
  },
  termsHeaderTitle: {
    fontSize: 17,
    fontFamily: "Inter_600SemiBold",
    color: Colors.light.onSurface,
  },
  termsCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.light.primaryContainer,
    justifyContent: "center",
    alignItems: "center",
  },
  termsScroll: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 24,
  },
  termsSection: {
    gap: 8,
  },
  termsSectionTitle: {
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    color: Colors.light.primary,
    letterSpacing: 0.2,
  },
  termsSectionTitleMain: {
    fontSize: 16,
    color: Colors.light.onSurface,
  },
  termsSectionBody: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: Colors.light.textSecondary,
    lineHeight: 22,
  },
});
